// This file is autogenerated – run `ant apidocs` to update it

import {
    ApiDataObject as CoreApiDataObject,
} from '../../core/'

export interface Attribute extends CoreApiDataObject {
     attributeId: any;
     content: string;
     type: string;
}

export interface Content extends CoreApiDataObject {
     contentId: string;
     contentTypeId: string;
     name: string;
     slug: string;
     attributes: Attribute[];
     /**
      * Access original object from backend
      *
      * This should only be used if you need very specific features
      * right NOW. Please notify Frontastic about your need so that
      * we can integrate those twith the common API. Any usage off
      * this property might make your code unstable against future
      * changes.
      */
     dangerousInnerContent?: any;
}
