// This file is autogenerated – run `ant apidocs` to update it

import {
    ApiDataObject as CoreApiDataObject,
} from '../../core/'

export interface Attribute extends CoreApiDataObject {
     attributeId: any;
     content: string;
     type: string;
}

export interface Content extends CoreApiDataObject {
     contentId: string;
     contentTypeId: string;
     name: string;
     slug: string;
     attributes: Attribute[];
     dangerousInnerContent?: any;
}
