// This file is autogenerated – run `ant apidocs` to update it

import {
    ApiDataObject as CoreApiDataObject,
} from '../core/'

import {
    Address as AccountAddress,
} from '../account/'

import {
    Translatable as Translatable,
} from '../'

export interface Cart extends CoreApiDataObject {
     cartId: string;
     cartVersion?: string;
     lineItems: LineItem[];
     email?: string;
     birthday?: any /* \DateTimeImmutable */;
     shippingInfo?: null | ShippingInfo;
     shippingMethod?: null | ShippingMethod;
     shippingAddress?: null | AccountAddress;
     billingAddress?: null | AccountAddress;
     sum: number;
     currency: string;
     payments: Payment[];
     discountCodes: Discount[];
     taxed?: null | Tax;
     dangerousInnerCart?: any;
}

export interface Discount extends CoreApiDataObject {
     discountId: string;
     code: string;
     state: string;
     name: Translatable;
     description?: Translatable;
     discountedAmount?: null | number;
     dangerousInnerDiscount?: any;
}

export interface LineItem extends CoreApiDataObject {
     lineItemId: string;
     name?: string;
     type: string;
     count: number;
     price: number;
     discountedPrice?: null | number;
     discountTexts?: any;
     discounts?: Discount[];
     totalPrice: number;
     currency: string;
     isGift: boolean;
     dangerousInnerItem?: any;
}

export interface Order extends Cart {
     orderId?: string;
     orderVersion?: string;
     orderState?: string;
     createdAt?: any /* \DateTimeImmutable */;
     dangerousInnerOrder?: any;
}

export interface Payment extends CoreApiDataObject {
     id: string;
     paymentProvider: string;
     paymentId: string;
     amount: number;
     currency: string;
     debug?: string;
     paymentStatus: string;
     version?: number;
     paymentMethod: string;
     paymentDetails?: any | null;
}

export interface ShippingMethod extends CoreApiDataObject {
     shippingMethodId?: string;
     name?: string;
     price?: number;
     description?: string;
     rates?: null | ShippingRate[];
     dangerousInnerShippingMethod?: null | any;
}

export interface Tax extends CoreApiDataObject {
     amount: number;
     currency: string;
     taxPortions?: TaxPortion[];
}

export interface TaxPortion extends CoreApiDataObject {
     amount?: number;
     currency?: string;
     name?: string;
     rate?: number;
}
