---
name: "Frontastic Common Library"
source: src
target: docs
autoloader: vendor/autoload.php
nameSpace: "\\Frontastic\\Common"
files:
 - php/*.php
 - php/*/*.php
 - php/*/*/*.php
 - php/*/*/*/*.php
