---
name: "Frontastic Common Library"
source: src
target: docs
autoloader: vendor/autoload.php
nameSpace: "\\Frontastic\\Common"
files:
 - php/AccountApiBundle/Domain/AccountApi/LifecycleEventDecorator/BaseImplementation.php
 - php/AccountApiBundle/Domain/AccountApi.php
 - php/AccountApiBundle/Domain/Account.php
 - php/AccountApiBundle/Domain/AccountService.php
 - php/AccountApiBundle/Domain/Address.php
 - php/AccountApiBundle/Domain/AuthentificationInformation.php
 - php/AccountApiBundle/Domain/Group.php
 - php/AccountApiBundle/Domain/MetaData.php
 - php/AccountApiBundle/Domain/Session.php
 - php/CartApiBundle/Domain/CartApiFactory.php
 - php/CartApiBundle/Domain/CartApi/LifecycleEventDecorator/BaseImplementation.php
 - php/CartApiBundle/Domain/CartApi.php
 - php/CartApiBundle/Domain/Cart.php
 - php/CartApiBundle/Domain/Discount.php
 - php/CartApiBundle/Domain/LineItem.php
 - php/CartApiBundle/Domain/LineItem/Variant.php
 - php/CartApiBundle/Domain/OrderIdGenerator.php
 - php/CartApiBundle/Domain/OrderIdGenerator/Random.php
 - php/CartApiBundle/Domain/Order.php
 - php/CartApiBundle/Domain/Payment.php
 - php/CartApiBundle/Domain/ShippingMethod.php
 - php/ContentApiBundle/Domain/AttributeFilter.php
 - php/ContentApiBundle/Domain/ContentApi/Attribute.php
 - php/ContentApiBundle/Domain/ContentApi/Contentful/LocaleMapper.php
 - php/ContentApiBundle/Domain/ContentApi/Contentful/NoopLocaleMapper.php
 - php/ContentApiBundle/Domain/ContentApi/Content.php
 - php/ContentApiBundle/Domain/ContentApi/LifecycleEventDecorator/BaseImplementation.php
 - php/ContentApiBundle/Domain/ContentApi.php
 - php/ContentApiBundle/Domain/ContentType.php
 - php/ContentApiBundle/Domain/Query.php
 - php/ContentApiBundle/Domain/Result.php
 - php/ProductApiBundle/Domain/Category.php
 - php/ProductApiBundle/Domain/DefaultProductApiFactory.php
 - php/ProductApiBundle/Domain/ProductApi/Facets.php
 - php/ProductApiBundle/Domain/ProductApiFactory.php
 - php/ProductApiBundle/Domain/ProductApi/LifecycleEventDecorator/BaseImplementation.php
 - php/ProductApiBundle/Domain/ProductApi/Locale.php
 - php/ProductApiBundle/Domain/ProductApi.php
 - php/ProductApiBundle/Domain/ProductApi/Query/CategoryQuery.php
 - php/ProductApiBundle/Domain/ProductApi/Query/Facet.php
 - php/ProductApiBundle/Domain/ProductApi/Query/Filter.php
 - php/ProductApiBundle/Domain/ProductApi/Query.php
 - php/ProductApiBundle/Domain/ProductApi/Query/ProductQueryFactory.php
 - php/ProductApiBundle/Domain/ProductApi/Query/ProductQuery.php
 - php/ProductApiBundle/Domain/ProductApi/Query/ProductTypeQuery.php
 - php/ProductApiBundle/Domain/ProductApi/Query/RangeFacet.php
 - php/ProductApiBundle/Domain/ProductApi/Query/RangeFilter.php
 - php/ProductApiBundle/Domain/ProductApi/Query/TermFacet.php
 - php/ProductApiBundle/Domain/ProductApi/Query/TermFilter.php
 - php/ProductApiBundle/Domain/ProductApi/Result/Facet.php
 - php/ProductApiBundle/Domain/ProductApi/Result.php
 - php/ProductApiBundle/Domain/ProductApi/Result/RangeFacet.php
 - php/ProductApiBundle/Domain/ProductApi/Result/TermFacet.php
 - php/ProductApiBundle/Domain/ProductApi/Result/Term.php
 - php/ProductApiBundle/Domain/Product.php
 - php/ProductApiBundle/Domain/ProductType.php
 - php/ProductApiBundle/Domain/Variant.php
 - php/ProjectApiBundle/Domain/Attribute.php
 - php/ProjectApiBundle/Domain/ProjectApi.php
 - php/ReplicatorBundle/Domain/Command.php
 - php/ReplicatorBundle/Domain/Customer.php
 - php/ReplicatorBundle/Domain/CustomerService.php
 - php/ReplicatorBundle/Domain/Endpoint.php
 - php/ReplicatorBundle/Domain/EndpointService.php
 - php/ReplicatorBundle/Domain/Project.php
 - php/ReplicatorBundle/Domain/RequestVerifier.php
 - php/ReplicatorBundle/Domain/Result.php
 - php/ReplicatorBundle/Domain/SequenceProvider.php
 - php/ReplicatorBundle/Domain/Source.php
 - php/ReplicatorBundle/Domain/Target.php
 - php/WishlistApiBundle/Domain/LineItem.php
 - php/WishlistApiBundle/Domain/LineItem/Variant.php
 - php/WishlistApiBundle/Domain/WishlistApiFactory.php
 - php/WishlistApiBundle/Domain/WishlistApi/LifecycleEventDecorator/BaseImplementation.php
 - php/WishlistApiBundle/Domain/WishlistApi.php
 - php/WishlistApiBundle/Domain/Wishlist.php
 - php/EnvironmentResolver.php
 - php/HttpClient/Configuration.php
 - php/HttpClient/Options.php
 - php/HttpClient.php
 - php/HttpClient/Response.php
 - php/JsonSerializer.php
 - php/Translatable.php
