language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'

install:
  - yarn install
  - composer install
  - mkdir ../../integration
  - echo ewogICAgImV4dGVuZHMiOiBbInN0YW5kYXJkIiwgInJlYWN0LWFwcCIsICJzdGFuZGFyZC1yZWFjdCJdLAogICAgInBhcnNlck9wdGlvbnMiOiB7CiAgICAgICAgImVjbWFWZXJzaW9uIjogNiwKICAgICAgICAiZWNtYUZlYXR1cmVzIjogewogICAgICAgICAgICAianN4IjogdHJ1ZSwKICAgICAgICAgICAgIm1vZHVsZXMiOiB0cnVlCiAgICAgICAgfQogICAgfSwKICAgICJlbnYiOiB7CiAgICAgICAgImVzNiI6IHRydWUKICAgIH0sCiAgICAicnVsZXMiOiB7CiAgICAgICAgImNvbW1hLWRhbmdsZSI6IFsyLCAiYWx3YXlzLW11bHRpbGluZSJdLAogICAgICAgICJjdXJseSI6IFsiZXJyb3IiLCAiYWxsIl0sCiAgICAgICAgImRlZmF1bHQtY2FzZSI6IDEsCiAgICAgICAgImluZGVudCI6IFsyLCA0XSwKICAgICAgICAibm8tbmVzdGVkLXRlcm5hcnkiOiAwLAogICAgICAgICJuby11bnVzZWQtdmFycyI6IDEsCiAgICAgICAgIm5vLXVzZS1iZWZvcmUtZGVmaW5lIjogMCwKICAgICAgICAib2JqZWN0LWN1cmx5LXNwYWNpbmciOiBbImVycm9yIiwgImFsd2F5cyJdLAogICAgICAgICJvcGVyYXRvci1saW5lYnJlYWsiOiBbMiwgImFmdGVyIiwgeyAib3ZlcnJpZGVzIjogeyAiOiI6ICJpZ25vcmUiLCAiPyI6ICJpZ25vcmUiIH0gfV0sCiAgICAgICAgInByZWZlci1yZWZsZWN0IjogMCwKICAgICAgICAicmVhY3QvanN4LWluZGVudCI6IFsiZXJyb3IiLCA0XSwKICAgICAgICAiYXJyb3ctYm9keS1zdHlsZSI6IFsiZXJyb3IiLCAiYWx3YXlzIl0sCiAgICAgICAgImluZGVudCI6IFsiZXJyb3IiLCA0LCB7ICJpZ25vcmVkTm9kZXMiOiBbIkpTWEVsZW1lbnQgKiJdIH1dLAogICAgICAgICJyZWFjdC9qc3gtaW5kZW50LXByb3BzIjogWyJlcnJvciIsIDRdLAogICAgICAgICJqc3gtYTExeS9ocmVmLW5vLWhhc2giOiAib2ZmIiwKICAgICAgICAianN4LWExMXkvYW5jaG9yLWlzLXZhbGlkIjogWzBdLAogICAgICAgICJzdHJpY3QiOiAxLAogICAgICAgICJyZWFjdC9ib29sZWFuLXByb3AtbmFtaW5nIjogMSwKICAgICAgICAicHJlZmVyLWNvbnN0IjogMCwKICAgICAgICAicXVvdGUtcHJvcHMiOiAwLAogICAgICAgICJsaW5lcy1iZXR3ZWVuLWNsYXNzLW1lbWJlcnMiOiAwCiAgICB9LAogICAgImdsb2JhbHMiOiB7CiAgICAgICAgIndpbmRvdyI6IHRydWUKICAgIH0KfQo= | base64 -d > ../../integration/eslint.config.json

script:
  - yarn run test
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyse
  - vendor/bin/phpcs --extensions=php --standard=PSR2 src/php/
