// This file is autogenerated – run `ant apidocs` to update it

import {
    ApiDataObject as CoreApiDataObject,
} from '../core/'

export interface LineItem extends CoreApiDataObject {
     lineItemId: string;
     name: string;
     type: string;
     addedAt: any /* \DateTimeImmutable */;
     count: number;
     /**
      * Access original object from backend
      *
      * This should only be used if you need very specific features
      * right NOW. Please notify Frontastic about your need so that
      * we can integrate those twith the common API. Any usage off
      * this property might make your code unstable against future
      * changes.
      */
     dangerousInnerItem?: any;
}

/**
 * Class Wishlist
 */
export interface Wishlist extends CoreApiDataObject {
     wishlistId: string;
     wishlistVersion?: string;
     anonymousId?: string;
     accountId?: string;
     name: string[];
     lineItems: LineItem[];
     /**
      * Access original object from backend
      *
      * This should only be used if you need very specific features
      * right NOW. Please notify Frontastic about your need so that
      * we can integrate those twith the common API. Any usage off
      * this property might make your code unstable against future
      * changes.
      */
     dangerousInnerWishlist?: any;
}
