// This file is autogenerated – run `ant apidocs` to update it

export interface Command {
     command: string;
     channel: string;
     customer: string;
     payload: any;
}

export interface Customer {
     name: string;
     secret: string;
     edition: string;
     hasPaasModifications: boolean;
     /**
      * Number of available Frontastic Machines
      */
     machineLimit: number;
     /**
      * Frontastic Machines Map to define providers use in each region
      */
     machineRegionToProviderMap: any;
     features: any;
     /**
      * Used to indicate this customer is only "half" configured or similar.
      */
     isTransient: boolean;
     configuration: any;
     environments: any;
     projects: Project[];
}

export interface Endpoint {
     name: string;
     url: string;
     push: boolean;
     environment: string;
}

export interface Project {
     projectId: string;
     name: string;
     customer: string;
     /**
      * In the config this is the `secret`.
      */
     apiKey: string;
     previewUrl?: string;
     preview?: any;
     publicUrl: string;
     webpackPort: number;
     ssrPort: number;
     configuration: any;
     /**
      * Additional external project data from sources like tideways. Does not
      * follow any defined schema.
      */
     data: any;
     languages: string[];
     defaultLanguage: string;
     projectSpecific: string[];
     endpoints: Endpoint[];
}

export interface Result {
     ok: boolean;
     payload: any;
     message?: string;
     file?: string;
     line?: number;
     stack?: any;
}
