// This file is autogenerated – run `ant apidocs` to update it

import {
    LineItem as WishlistLineItem,
} from '../'

import {
    Variant as ProductVariant,
} from '../../product/'

export interface Variant extends WishlistLineItem {
     variant?: ProductVariant;
     type?: string;
}
