// This file is autogenerated – run `ant apidocs` to update it

export interface SapLocale {
     /**
      * ISO code
      */
     languageCode: string;
     /**
      * ISO code
      */
     currencyCode: string;
}
