// This file is autogenerated – run `ant apidocs` to update it

export interface Attribute {
     attributeId: string;
     type: string;
     label?: Map<string, string> | null;
     values?: null | any;
}
