// This file is autogenerated – run `ant apidocs` to update it

import {
    ApiDataObject as CoreApiDataObject,
} from '../core/'

export interface Attribute extends CoreApiDataObject {
     attributeId: string;
     type: string;
     label?: Map<string, string> | null;
     values?: null | any;
}
