// This file is autogenerated – run `ant apidocs` to update it

export interface ShopwareLocale {
     country?: string;
     countryId?: string;
     currency?: string;
     currencyId?: string;
     language?: string;
     languageId?: string;
}
