// This file is autogenerated – run `ant apidocs` to update it

export interface Configuration {
     options?: Options;
     /**
      * List (not hashmap!) of headers
      */
     defaultHeaders?: string[];
     signatureSecret?: null | string;
     collectStats?: boolean;
     collectProfiling?: boolean;
}

export interface Options {
     /**
      * Timeout for the complete request in seconds
      */
     timeout?: number | number;
}

export interface Response {
     /**
      * Response HTTP status code
      */
     status: number;
     /**
      * The HTTP headers from the response as a plain array
      */
     headers: string[];
     /**
      * Response body
      */
     body?: string;
     /**
      * Raw HTTP output response
      */
     rawApiOutput?: any /* \Psr\Http\Message\ResponseInterface */;
}
