// This file is autogenerated – run `ant apidocs` to update it

export interface Configuration {
     options?: Options;
     defaultHeaders?: string[];
     signatureSecret?: null | string;
     collectStats?: boolean;
     collectProfiling?: boolean;
}

export interface Options {
     timeout?: number | number;
}

export interface Response {
     status?: number;
     headers?: string[];
     body?: string;
     rawApiOutput?: any /* \Psr\Http\Message\ResponseInterface */;
}
