<?php

namespace Frontastic\Common\SpecificationBundle\Domain\Schema;

class GroupFieldConfiguration extends FieldConfiguration
{
    private int $min = 1;

    private ?int $max = null;

    public static function doCreateFromSchema(string $type, array $fieldSchema): FieldConfiguration
    {
        /** @var self $schema */
        $schema = parent::doCreateFromSchema($type, $fieldSchema); // TODO: Change the autogenerated stub

        $schema->min = self::getSchemaValue($fieldSchema, 'min', 1);
        $schema->max = self::getSchemaValue($fieldSchema, 'max', null);

        return $schema;
    }

    public function processValueIfRequired($value)
    {
        if (!is_array($value)) {
            $value = [];
        }

        while (count($value) < $this->min) {
            $value[] = $this->generateDefaultElement();
        }

        if ($this->max !== null && count($value) > $this->max) {
            $value = array_slice($value, 0, $this->max);
        }
        return $value;
    }

    private function generateDefaultElement()
    {
        // TODO: Generate proper default for nested elements
        return [];
    }
}
