// This file is autogenerated – run `ant apidocs` to update it

import {
    ApiDataObject as CoreApiDataObject,
} from '../core/'

export interface Account extends CoreApiDataObject {
     accountId: string;
     email: string;
     salutation?: string;
     firstName?: string;
     lastName?: string;
     birthday?: any /* \DateTime */;
     groups: Group[];
     confirmationToken?: string;
     confirmed?: boolean;
     tokenValidUntil?: any /* \DateTime */;
     addresses: Address[];
     authToken?: string | null;
     dangerousInnerAccount?: any;
}

export interface Address extends CoreApiDataObject {
     addressId: string;
     salutation?: string;
     firstName?: string;
     lastName?: string;
     streetName?: string;
     streetNumber?: string;
     additionalStreetInfo?: string;
     additionalAddressInfo?: string;
     postalCode?: string;
     city?: string;
     country?: string;
     state?: string;
     phone?: string;
     isDefaultBillingAddress?: boolean;
     isDefaultShippingAddress?: boolean;
     dangerousInnerAddress?: any;
}

export interface AuthentificationInformation extends CoreApiDataObject {
     email: string;
     password: string;
     newPassword: string;
}

export interface Group extends CoreApiDataObject {
     groupId: string;
     name: string;
     permissions: string[];
}

export interface MetaData extends CoreApiDataObject {
     author: string;
     changed: any /* \DateTimeImmutable */;
}

export interface PasswordResetToken extends CoreApiDataObject {
     email: string;
     confirmationToken?: string | null;
     tokenValidUntil?: any /* \DateTime */ | null;
}

export interface Session extends CoreApiDataObject {
     loggedIn: boolean;
     account?: Account;
     message?: string;
}
